---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r loading tidyverse command}
# Download tidyverse 
# tidyverse is already installed and dplyr and ggplot2 are included in the tidyverse package.
library(tidyverse)
```

```{r loading gapminder dataset into a data frame}
# Load the full gapminder dataset into a data frame
# install.packages("gapminder")
library(gapminder)
data(gapminder)
gm <- gapminder
gm1<- as.data.frame(gm) ### gm1=gm
```

```{r summary of the data frame}
# summary of the gapminder 
summary(gm1)
```

```{r histogram of the (log-transformed)populations column}
# histogram of log(pop)
logpop <- log(gm1$pop)
hist(logpop, main="histogram of the log-transformed population")
```

```{r scatterplot of life expectancy vs. log-transformed gdp-per-capita}
# scatterplot of life expectancy vs log(gdp per capita)
loggdp<- log(gm1$gdpPercap)
plot(loggdp,gm1$lifeExp, main="scatterplot of life expectacy vs log(GDP per capita)", xlab="log transforemd GDP per capita",ylab="life expectancy at birth in years")
```

```{r t-test of life expectancy differences between South Africa and Ireland}
# The null hypothesis is that the life-expectancy mean difference between South Africa and Ireland is 0.
# The alternative hypothesis is that the life-expectancy means difference is not 0.
# Set the level of significance equal to 0.05. If the p-value is less than 0.05, reject the null hypothesis.
# First, do the pipe operation to select country and life expectancy variables and then, filter the countries if countries are South Africa or Ireland. 
df <- gm1 %>%
  select(country, lifeExp) %>%
  filter(country == "South Africa" | 
          country == "Ireland") %>%
  group_by(country) 

# Then, do the t-test. 
t.test(data=df, lifeExp ~ country, alternative="two.sided",mu=0,conf.level =0.95)

# Since the p-value =4.466e-09 is less than 0.05, we can conclude that the true difference in means is not 0.
```



```{r single-plot of life expectancy vs. gdp-per-capita, colored by continent, and dot-size by population, with the smooth function}
# ggplot of life exp vs. gdpPercap 
plot_lifeExpandgdp <- gm1 %>%
  # grap gdp-per-capita less than 50000
  filter(gdpPercap < 50000) %>%
  mutate(log_gdp=log(gdpPercap))
ggplot(data=plot_lifeExpandgdp, aes(x=log_gdp,y=lifeExp,color=continent,size=pop)) +
  geom_point(alpha=0.3) +
  geom_smooth(method=lm) +
  ylab("life expectancy at birth in years") +
  xlab("logged gdp per capita") +
  ggtitle("plot of life expextance vs. gdp per capita")
```


```{r his faceted ggplot scatterplot, colored by year, faceted by continent, with the smooth function}
# faceting ggplot
ggplot(data=plot_lifeExpandgdp, aes(x=log_gdp,y=lifeExp,color=year,size=pop)) +
  geom_point(alpha=0.3) +
  geom_smooth(method=lm) +
  ylab("life expectancy at birth in years") +
  xlab("logged gdp per capita") +
  ggtitle("plot of life expextance vs. gdp per capita") +
  facet_wrap(~ continent)
```





```{r linear model test of life expectancy by gdp-per-capita and population}
lm_lifeExpbygdp <- lm(lifeExp ~ gdpPercap + pop,data=gm1)
summary(lm_lifeExpbygdp)
```


